# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0153127bbf9e6b167c59fe5c701b16f05ce2acf31a17311dcd6c44a467afdd835497fff622c508d2d4fb3a11d79363006d97b21d54a6500072d6b5ce0a1ced1a

test:
  secret_key_base: 5fef54386017f659fb93739cf26ec6663e852eb1538baccf5724cde722eb5c64402ad1e57e4f0b8bc7a836a547043f24277da7e5e2d20b77b8d6bf818e749651

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
